channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - cmake >= 3.18
  - gcc
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - pytest
    - pytest-cov
    - pytest-mock
    - expecttest
    - pyyaml
    - scipy
    - hydra-core
