env_name: HalfCheetah-v4
env_task: ""
env_library: gym
async_collection: 1
record_video: 0
normalize_rewards_online: 1
normalize_rewards_online_scale: 5
#frames_per_batch: 1
frame_skip: 1
frames_per_batch: 1024
#optim_steps_per_batch: 1
optim_steps_per_batch: 1024
batch_size: 256
total_frames: 1000000
prb: 1
lr: 3e-4
ou_exploration: 1
multi_step: 0
init_random_frames: 25000
activation: elu
gSDE: 0
from_pixels: 0
collector_devices: [cpu]
#collector_devices: [cuda:1,cuda:2,cuda:1,cuda:2]
env_per_collector: 2
#env_per_collector: 8
num_workers: 2
#num_workers: 32
record_interval: 10
max_frames_per_traj: -1
init_env_steps: 10000
record_frames: 10000
loss_function: l2
buffer_prefetch: 64
